require:
  - rubocop-performance

AllCops:
  NewCops: enable

inherit_mode:
  merge:
    - Include
    - Exclude

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented
Layout/MultilineOperationIndentation:
  EnforcedStyle: indented
Layout/ParameterAlignment:
  EnforcedStyle: with_fixed_indentation
Layout/MultilineArrayBraceLayout:
  EnforcedStyle: new_line
Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent
Layout/FirstArgumentIndentation:
  EnforcedStyle: consistent
Layout/FirstArrayElementLineBreak:
  Enabled: true
Layout/FirstMethodArgumentLineBreak:
  Enabled: true
Layout/LineLength:
  Max: 100

Metrics/BlockLength:
  Exclude:
    - 'benchmark/*'
